// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PointsTracker.Infrastructure.Persistence;

#nullable disable

namespace PointsTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518101151_AddMatchScorerLinks")]
    partial class AddMatchScorerLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PointsTracker.Domain.Entities.CleanupAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<string>("TargetIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("target_ids");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_cleanup_audit_log_occurred");

                    b.ToTable("cleanup_audit_log", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BeachAutoSwitchSides")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("beach_auto_switch_sides");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomLastSetPoints")
                        .HasColumnType("integer")
                        .HasColumnName("custom_last_set_points");

                    b.Property<int?>("CustomPointsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("custom_points_per_set");

                    b.Property<int?>("CustomSetsToWin")
                        .HasColumnType("integer")
                        .HasColumnName("custom_sets_to_win");

                    b.Property<int?>("CustomTimeoutDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("custom_timeout_duration_seconds");

                    b.Property<int?>("CustomTimeoutsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("custom_timeouts_per_set");

                    b.Property<int?>("CustomTotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("custom_total_sets");

                    b.Property<bool?>("CustomWinByTwo")
                        .HasColumnType("boolean")
                        .HasColumnName("custom_win_by_two");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IndoorSwitchEverySets")
                        .HasColumnType("integer")
                        .HasColumnName("indoor_switch_every_sets");

                    b.Property<Guid?>("LinkedTournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_tournament_id");

                    b.Property<Guid?>("LinkedTournamentMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_tournament_match_id");

                    b.Property<string>("LinkedTournamentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_tournament_name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<bool>("PendingSideSwitchConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pending_side_switch_confirmation");

                    b.Property<string>("SessionTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token_hash");

                    b.Property<int>("SideSwitchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("side_switch_count");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TeamAName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_a_name");

                    b.Property<string>("TeamBName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_b_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTournamentId")
                        .HasFilter("linked_tournament_id IS NOT NULL");

                    b.HasIndex("OwnerUserId")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsUndone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_undone");

                    b.Property<Guid?>("RelatedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_event_id");

                    b.Property<short>("ScoreAAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("score_a_after");

                    b.Property<short>("ScoreABefore")
                        .HasColumnType("smallint")
                        .HasColumnName("score_a_before");

                    b.Property<short>("ScoreBAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("score_b_after");

                    b.Property<short>("ScoreBBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("score_b_before");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.HasKey("Id");

                    b.HasIndex("CounterId", "CreatedAt");

                    b.ToTable("counter_events", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("ScoreA")
                        .HasColumnType("integer")
                        .HasColumnName("score_a");

                    b.Property<int>("ScoreB")
                        .HasColumnType("integer")
                        .HasColumnName("score_b");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Winner")
                        .HasColumnType("text")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.ToTable("counter_sets", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.MatchScorerLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("GrantedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_to_user_id");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("match_scorer_links", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.RoleAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor");

                    b.Property<string>("FromRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_role");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("ToRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_role_audit_log_user_occurred");

                    b.ToTable("role_audit_log", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.ShareToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("CounterId")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("share_tokens", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AdvancePerGroup")
                        .HasColumnType("integer")
                        .HasColumnName("advance_per_group");

                    b.Property<bool>("BeachAutoSwitchSides")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("beach_auto_switch_sides");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomLastSetPoints")
                        .HasColumnType("integer")
                        .HasColumnName("custom_last_set_points");

                    b.Property<int?>("CustomPointsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("custom_points_per_set");

                    b.Property<int?>("CustomSetsToWin")
                        .HasColumnType("integer")
                        .HasColumnName("custom_sets_to_win");

                    b.Property<int?>("CustomTimeoutDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("custom_timeout_duration_seconds");

                    b.Property<int?>("CustomTimeoutsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("custom_timeouts_per_set");

                    b.Property<int?>("CustomTotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("custom_total_sets");

                    b.Property<bool?>("CustomWinByTwo")
                        .HasColumnType("boolean")
                        .HasColumnName("custom_win_by_two");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int?>("FinalLastSetPoints")
                        .HasColumnType("integer")
                        .HasColumnName("final_last_set_points");

                    b.Property<int?>("FinalPointsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("final_points_per_set");

                    b.Property<int?>("FinalSetsToWin")
                        .HasColumnType("integer")
                        .HasColumnName("final_sets_to_win");

                    b.Property<int?>("FinalTimeoutDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("final_timeout_duration_seconds");

                    b.Property<int?>("FinalTimeoutsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("final_timeouts_per_set");

                    b.Property<int?>("FinalTotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("final_total_sets");

                    b.Property<bool?>("FinalWinByTwo")
                        .HasColumnType("boolean")
                        .HasColumnName("final_win_by_two");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<int?>("GroupCount")
                        .HasColumnType("integer")
                        .HasColumnName("group_count");

                    b.Property<int?>("IndoorSwitchEverySets")
                        .HasColumnType("integer")
                        .HasColumnName("indoor_switch_every_sets");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int?>("SemifinalLastSetPoints")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_last_set_points");

                    b.Property<int?>("SemifinalPointsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_points_per_set");

                    b.Property<int?>("SemifinalSetsToWin")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_sets_to_win");

                    b.Property<int?>("SemifinalTimeoutDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_timeout_duration_seconds");

                    b.Property<int?>("SemifinalTimeoutsPerSet")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_timeouts_per_set");

                    b.Property<int?>("SemifinalTotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("semifinal_total_sets");

                    b.Property<bool?>("SemifinalWinByTwo")
                        .HasColumnType("boolean")
                        .HasColumnName("semifinal_win_by_two");

                    b.Property<string>("SessionTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_type");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SessionTokenHash")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.TournamentMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BracketSide")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bracket_side");

                    b.Property<Guid?>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("group_number");

                    b.Property<Guid?>("LoserParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("loser_participant_id");

                    b.Property<bool>("LoserToSideA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("loser_to_side_a");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer")
                        .HasColumnName("match_number");

                    b.Property<Guid?>("NextLoserMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_loser_match_id");

                    b.Property<Guid?>("NextMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_match_id");

                    b.Property<Guid?>("ParticipantAId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_a_id");

                    b.Property<Guid?>("ParticipantBId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_b_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WinnerParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_participant_id");

                    b.Property<bool>("WinnerToSideA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("winner_to_side_a");

                    b.HasKey("Id");

                    b.HasIndex("CounterId")
                        .HasFilter("counter_id IS NOT NULL");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournament_matches", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.TournamentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("TournamentId", "TeamName")
                        .IsUnique();

                    b.ToTable("tournament_participants", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("RoleSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_source");

                    b.Property<DateTime>("RoleUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_updated_at");

                    b.Property<string>("RoleUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_updated_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterEvent", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("Events")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterSet", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("Sets")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.MatchScorerLink", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.TournamentMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.ShareToken", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("ShareTokens")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.TournamentMatch", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Tournament", null)
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.TournamentParticipant", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Tournament", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.Counter", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sets");

                    b.Navigation("ShareTokens");
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
