// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PointsTracker.Infrastructure.Persistence;

#nullable disable

namespace PointsTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PointsTracker.Domain.Entities.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SessionTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TeamAName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_a_name");

                    b.Property<string>("TeamBName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_b_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<short>("ScoreAAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("score_a_after");

                    b.Property<short>("ScoreABefore")
                        .HasColumnType("smallint")
                        .HasColumnName("score_a_before");

                    b.Property<short>("ScoreBAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("score_b_after");

                    b.Property<short>("ScoreBBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("score_b_before");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.HasKey("Id");

                    b.HasIndex("CounterId", "CreatedAt");

                    b.ToTable("counter_events", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("ScoreA")
                        .HasColumnType("integer")
                        .HasColumnName("score_a");

                    b.Property<int>("ScoreB")
                        .HasColumnType("integer")
                        .HasColumnName("score_b");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Winner")
                        .HasColumnType("text")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.ToTable("counter_sets", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.ShareToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("CounterId")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("share_tokens", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterEvent", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("Events")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.CounterSet", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("Sets")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.ShareToken", b =>
                {
                    b.HasOne("PointsTracker.Domain.Entities.Counter", null)
                        .WithMany("ShareTokens")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointsTracker.Domain.Entities.Counter", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sets");

                    b.Navigation("ShareTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
